### ISSUE TITLE
Are prompts included in the perturbation / likelihood computation?

### ISSUE THREAD

**Issue by martiansideofthemoon** [eric-mitchell/detect-gpt#1]
Hi @eric-mitchell,
Thanks for setting up this clean implementation! I had a quick question about the method.

Do you include the prompts as a prefix to the samples while you perform perturbations / calculate likelihood?

From [here](https://github.com/eric-mitchell/detect-gpt/blob/main/run.py#L204) and [here](https://github.com/eric-mitchell/detect-gpt/blob/main/run.py#L240) it seems like prompts are included.

I was wondering if very long prompts (relative to the generation length) increase the false-positive rate?

Thank you!

**Comment by eric-mitchell** [comment]
Thanks for checking out the code!

Yes, we include prompts in perturbations/likelihood calculation, but we don't assume we know which tokens are prompt tokens and which are generated tokens. With this setup, I'd expect you're right that if most tokens are prompt tokens, rather than model-generated tokens, detection quality will suffer. It's possible this is one reason why pubmed performance is lower (though I don't know this to be true), since the questions in pubmedqa may be longer than the shorter prefixes we use to generate data for the other datasets.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Kalpesh Krishna ***@***.***>
Sent: Tuesday, February 14, 2023 12:31:08 PM
To: eric-mitchell/detect-gpt ***@***.***>
Cc: Eric Anthony Mitchell ***@***.***>; Mention ***@***.***>
Subject: [eric-mitchell/detect-gpt] Are prompts used in the passage? (Issue #1)


Hi @eric-mitchell<https://github.com/eric-mitchell>,
Thanks for setting up this clean implementation! I had a quick question about the method.

Do you include the prompts as a prefix to the samples while you perform perturbations / calculate likelihood?

From here<https://github.com/eric-mitchell/detect-gpt/blob/main/run.py#L204> and here<https://github.com/eric-mitchell/detect-gpt/blob/main/run.py#L240> it seems like prompts are included.

I was wondering if very long prompts (relative to the generation length) increase the false-positive rate?

Thank you!

**Comment by martiansideofthemoon** [comment]
Hi @eric-mitchell,
Thank you for the quick reply! I'll close this issue for now.
