### ISSUE TITLE
There is something wrong when downloading the xsum dataset

### ISSUE THREAD

**Issue by stdliberX** [eric-mitchell/detect-gpt#6]
The program got stuck at line 627, data = datasets.load_dataset(dataset, split='train', cache_dir=cache_dir)[key], while running. I tried running this line of code separately in another project, then moving the downloaded xsum file to the ~/.cache, but the program still got stuck here every time. I also changed xsum to "enlish" to call custom_datasets.py, but the data would download partially and then stop downloading, and the program would get stuck at data = custom_datasets.load(dataset, cache_dir).
When the program got stuck, I checked my CPU, GPU, and they were not overloaded, my network signal was also good, I don't know what happened.

**Comment by eric-mitchell** [comment]
Sorry for the slow response- have had a lot going on! Thanks for checking out the repo.

Without an error message, it's hard to know. This shouldn't be related to your GPUs, since it's just downloading the data from HuggingFace. it could have been a temporary outage where the data was hosted. I'd also recommend usage a local hard disk (`cache_dir` arg to `datasets.load_dataset`) to download datasets, in case you're using an NFS path by default.

Feel free to re-open this issue if you're still having problems!
